services:
  - type: web
    name: buyworth
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install flask"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    healthCheckPath: "/health"
    healthCheckInterval: 30